spring:
  elasticsearch:
    rest:
      uris: http://192.168.1.118:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.1.118:9300
      cluster-name: elasticsearch